_wandb:
    value:
        cli_version: 0.22.3
        e:
            g54ium6ez6rk1tiggd8nuql876y2ejyg:
                codePath: training/glc_run_pinn_trainer.py
                codePathLocal: glc_run_pinn_trainer.py
                cpu_count: 20
                cpu_count_logical: 28
                disk:
                    /:
                        total: "501809635328"
                        used: "78751309824"
                email: lucas.kuhnen@posgrad.ufsc.br
                executable: /home/lucas-kuhnen-costa/miniconda3/envs/MScThesis/bin/python
                git:
                    commit: 6349e74ad62a597fdf530e0915c19b6e6db553db
                    remote: https://github.com/lucaskuhnencosta/institute_oil_gas_research
                host: LucasOptiPlex
                memory:
                    total: "33320550400"
                os: Linux-6.17.0-14-generic-x86_64-with-glibc2.39
                program: /home/lucas-kuhnen-costa/PycharmProjects/IOGR_StoAmaro/training/glc_run_pinn_trainer.py
                python: CPython 3.13.9
                root: /home/lucas-kuhnen-costa/PycharmProjects/IOGR_StoAmaro/training
                startedAt: "2026-03-05T04:11:29.470464Z"
                writerId: g54ium6ez6rk1tiggd8nuql876y2ejyg
        m: []
        python_version: 3.13.9
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 16
            "4": 3.13.9
            "5": 0.22.3
            "12": 0.22.3
            "13": linux-x86_64
K1_adam:
    value: 5000
K2_lbfgs:
    value: 2000
N_col:
    value: 20000
N_data:
    value: 20
N_val:
    value: 2000
device:
    value: cpu
epochs:
    value: 7000
learning_rate:
    value: 0.001
loss_func:
    value: MSELoss
lr_scheduler:
    value: null
mixed_precision:
    value: true
model:
    value: PINN
mse_f_scale_factors:
    value:
        - 1
        - 1
        - 1
optimizer:
    value: Adam
random_seed:
    value: 333333
u_max:
    value:
        - 1
        - 1
u_min:
    value:
        - 0.1
        - 0.2
y_max:
    value:
        - 4796.2
        - 1094.6
        - 11990.9
y_min:
    value:
        - 3032.55
        - 220.05
        - 6341.3
